### ISSUE TITLE
cant export templates dir to npm published package

### ISSUE THREAD

**Issue by tunnckoCore** [tunnckoCore/charlike#3]

**Comment by tunnckoCore** [comment]
@jonschlinkert @doowb, any ideas? I tried a few ways to add it to `files` field - only `"templates"`, `templates/` and even [adding each of the files](https://github.com/tunnckoCore/charlike/blob/master/package.json#L44-L55) in that dir - all failed.

Any thoughts what's happening?

**Comment by doowb** [comment]
Could be an npm bug (or yarn)... it might be looking at the `package.json` inside the `templates` dir for some reason.

**Comment by tunnckoCore** [comment]
ooh yea good point, thanks. i will try

**Comment by tunnckoCore** [comment]
Yes, that worked. :) Make sense.
